name: 'Samo build utility'
description: 'Samo build project, helm and docker utility.'
author: 'andrejpetras'
branding:
  icon: edit
  color: blue
outputs:
  stdout: # stdout of output
    description: 'The command output'  
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/entrypoint.sh"